/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vigenere;

import java.awt.BasicStroke;
import javax.swing.JComboBox;
import java.awt.BorderLayout;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author Owner
 */
public class MainInterface extends javax.swing.JFrame {
    //Global Variables
     EncryptPanel ePanel = new EncryptPanel();
     DecryptPanel dPanel = new DecryptPanel();
     BreakPanel bPanel = new BreakPanel();
     JPanel currentPanel= new JPanel();
     

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        this.setSize(690, 730);
        statsButton.setVisible(false);
        fullResultsButton.setVisible(false);
        guessKeyButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        title = new javax.swing.JLabel();
        optionsBox = new javax.swing.JComboBox();
        bodyPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inPrevTextA = new javax.swing.JLabel();
        outPrevTextA = new javax.swing.JLabel();
        textAreaIN = new java.awt.TextArea();
        textAreaOUT = new java.awt.TextArea();
        fullResultsButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        guessKeyButton = new javax.swing.JButton();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(690, 730));

        title.setFont(new java.awt.Font("Stencil Std", 1, 12)); // NOI18N
        title.setText("Vigenere Cipher");

        optionsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    Select...", "    Encrypt", "    Decrypt", "    Break" }));
        optionsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsBoxActionPerformed(evt);
            }
        });

        bodyPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bodyPanel.setPreferredSize(new java.awt.Dimension(350, 290));

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        fullResultsButton.setText("Full Results");
        fullResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullResultsButtonActionPerformed(evt);
            }
        });

        statsButton.setText("Generate Stats");
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });

        guessKeyButton.setText("Guessed Keys");
        guessKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessKeyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inPrevTextA, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(outPrevTextA, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(fullResultsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(guessKeyButton))
                            .addComponent(textAreaIN, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAreaOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(optionsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21))
                    .addComponent(inPrevTextA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAreaIN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outPrevTextA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullResultsButton)
                    .addComponent(statsButton)
                    .addComponent(guessKeyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAreaOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optionsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsBoxActionPerformed
        // TODO add your handling code here:
        JComboBox cb= (JComboBox) evt.getSource();
	String selectedOp = (String) cb.getSelectedItem(); 
        pack();
        bodyPanel.setLayout(new BorderLayout());
        currentPanel=updatePanel(selectedOp);
        bodyPanel.add(currentPanel);
        bodyPanel.repaint();
        setVisible(true);
        
        
        
    }//GEN-LAST:event_optionsBoxActionPerformed

    private void fullResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullResultsButtonActionPerformed
        
        String brokenfilename= BreakPanel.getBrokenFileName();
        try {
            Runtime.getRuntime().exec("notepad "+brokenfilename);
        } catch (IOException ex) {
            Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_fullResultsButtonActionPerformed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        DefaultCategoryDataset dataset= new DefaultCategoryDataset();
        double[] vals=BreakPanel.getICS();
        for(int i=0;i<vals.length;i++){
            dataset.setValue(vals[i],"IC" , Integer.toString(i+1));
        }
                
                
        JFreeChart chart=ChartFactory.createBarChart("Average IC for different Key Length", "Key Length", "IC", dataset,PlotOrientation.VERTICAL, false,true,false);
        CategoryPlot p= chart.getCategoryPlot();
        ValueMarker marker= new ValueMarker(0.065);
        marker.setLabel("English IC");
        marker.setLabelTextAnchor(TextAnchor.BASELINE_LEFT);
        BasicStroke stroke = new BasicStroke(2.2f);
        marker.setPaint(Color.BLUE);
        marker.setStroke(stroke);
        p.addRangeMarker(marker);
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame= new ChartFrame("Index of Coincidence for Key Lengths",chart);
        frame.setVisible(true);
        frame.setSize(650, 450);

    }//GEN-LAST:event_statsButtonActionPerformed

    private void guessKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessKeyButtonActionPerformed
        KeyList kl= new KeyList(BreakPanel.getKEYS());
        kl.setVisible(true);
        kl.setSize(320, 360);
        kl.setLocation(640, 350);
    }//GEN-LAST:event_guessKeyButtonActionPerformed
   public JPanel updatePanel(String type){
        String option = type.replaceAll("\\s", "");
        JPanel result=new JPanel();
        //always restart the textfield for all three panels
        BreakPanel.clearTextF();EncryptPanel.clearTextF();DecryptPanel.clearTextF();
       if(option.equals("Encrypt")){
            bodyPanel.removeAll();
            //currentPanel.setVisible(false);
            System.out.println(type);
            result =ePanel;
            inPrevTextA.setVisible(true);inPrevTextA.setText("Original Plaintext:");
            outPrevTextA.setVisible(true);outPrevTextA.setText("Encrypted text:");
            //repaint textAreas to be empty
            textAreaIN.setEditable(true);
            textAreaIN.setText("");
            textAreaOUT.setEditable(true);
            textAreaOUT.setText("");
            statsButton.setVisible(false);
            fullResultsButton.setVisible(false);
            guessKeyButton.setVisible(false);
            
            }
        else if(option.equals("Decrypt")){
            bodyPanel.removeAll();
            //currentPanel.setVisible(false);
            System.out.println(type);
            result=dPanel;
            inPrevTextA.setVisible(true);inPrevTextA.setText("Encrypted text:");
            outPrevTextA.setVisible(true);outPrevTextA.setText("Decrypted text:");
            //repaint textAreas to be empty
            textAreaIN.setEditable(true);
            textAreaIN.setText("");
            textAreaOUT.setEditable(true);
            textAreaOUT.setText("");
            statsButton.setVisible(false);
            fullResultsButton.setVisible(false);
            guessKeyButton.setVisible(false);
            
        }
        else if (option.equals("Break")){
            bodyPanel.removeAll();
            //currentPanel.setVisible(false);
            System.out.println(type);
            result=bPanel;
            inPrevTextA.setVisible(true);inPrevTextA.setText("Encrypted text:");
            outPrevTextA.setVisible(true);outPrevTextA.setText("Decrypted text:");
            //repaint textAreas to be empty
            textAreaIN.setEditable(true);
            textAreaIN.setText("");
            textAreaOUT.setEditable(true);
            textAreaOUT.setText("");
        }
        else if (option.equals("    Select...")){
            bodyPanel.removeAll();
            inPrevTextA.setVisible(false);
            outPrevTextA.setVisible(false);        
            statsButton.setVisible(false);
            fullResultsButton.setVisible(false);
            statsButton.setVisible(false);
            fullResultsButton.setVisible(false);
            guessKeyButton.setVisible(false);
        }
 
       return result;
   }
   
   public static void setInPrevTextA(String inText){
       textAreaIN.setText(inText);
       textAreaIN.setEditable(false);
   }
    public static void setOutPrevTextA(String outText,int from){
       if (from ==0){ 
       textAreaOUT.setText(outText);
       textAreaOUT.setEditable(false);
       }
       //if called from Break Panel just show the first decryption
       else{
       textAreaOUT.setText("This is a preview of the possible decryptions for the given ciphertext: \n"+outText);
       textAreaOUT.setEditable(false);}      
       
   }
   
    public static String getInPrevTextA(){
        return textAreaIN.getText();
    }
    
    
    public static void activateButtons(){
        statsButton.setVisible(true);
        fullResultsButton.setVisible(true);
        guessKeyButton.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private java.awt.Button button1;
    public static javax.swing.JButton fullResultsButton;
    public static javax.swing.JButton guessKeyButton;
    private javax.swing.JLabel inPrevTextA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox optionsBox;
    private javax.swing.JLabel outPrevTextA;
    public static javax.swing.JButton statsButton;
    public static java.awt.TextArea textAreaIN;
    public static java.awt.TextArea textAreaOUT;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
